function main_gui()
% MAIN_GUI  Graphical launcher for all analysis scripts.
%   Opens a GUI with buttons to run each segmentation and registration
%   case study. Automatically initializes project paths via setup.m.

    % Initialize project paths
    scriptDir = fileparts(mfilename('fullpath'));
    projectRoot = fullfile(scriptDir, '..');
    run(fullfile(projectRoot, 'setup.m'));

    % Create main figure
    f = figure('Name', 'Medical Image Analysis — Script Launcher', ...
               'Color', [0.95 0.95 0.95], ...
               'Position', [500 300 450 430]);

    %% === SECTION 1: SEGMENTATION ===
    uicontrol('Style', 'text', ...
              'String', 'Segmentation', ...
              'FontSize', 14, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', [0.95 0.95 0.95], ...
              'ForegroundColor', [0.15, 0.18, 0.22], ...
              'Position', [50 370 350 30]);

    segDir = fullfile(projectRoot, 'scripts', 'segmentation');

    uicontrol('Style', 'pushbutton', 'String', 'Kidney & Medulla', ...
              'FontSize', 12, 'Position', [100 330 250 30], ...
              'Callback', @(~,~) run(fullfile(segDir, 'seg_kidney_medulla.m')));

    uicontrol('Style', 'pushbutton', 'String', 'Ventricles (LV & RV)', ...
              'FontSize', 12, 'Position', [100 290 250 30], ...
              'Callback', @(~,~) run(fullfile(segDir, 'seg_ventricles.m')));

    uicontrol('Style', 'pushbutton', 'String', '3D Left Atrium', ...
              'FontSize', 12, 'Position', [100 250 250 30], ...
              'Callback', @(~,~) run(fullfile(segDir, 'seg_left_atrium_3d.m')));

    uicontrol('Style', 'pushbutton', 'String', 'Breast Lesion', ...
              'FontSize', 12, 'Position', [100 210 250 30], ...
              'Callback', @(~,~) run(fullfile(segDir, 'seg_breast_lesion.m')));

    %% === SECTION 2: REGISTRATION ===
    uicontrol('Style', 'text', ...
              'String', 'Registration', ...
              'FontSize', 14, ...
              'FontWeight', 'bold', ...
              'BackgroundColor', [0.95 0.95 0.95], ...
              'ForegroundColor', [0.15, 0.18, 0.22], ...
              'Position', [50 150 350 30]);

    regDir = fullfile(projectRoot, 'scripts', 'registration');

    uicontrol('Style', 'pushbutton', 'String', 'Translational Registration', ...
              'FontSize', 12, 'Position', [100 110 250 30], ...
              'Callback', @(~,~) run(fullfile(regDir, 'reg_translation.m')));

    uicontrol('Style', 'pushbutton', 'String', 'Rotational Registration', ...
              'FontSize', 12, 'Position', [100 70 250 30], ...
              'Callback', @(~,~) run(fullfile(regDir, 'reg_rotation.m')));

    %% === EXIT BUTTON ===
    uicontrol('Style', 'pushbutton', 'String', 'Exit', ...
              'FontSize', 12, 'BackgroundColor', [0.8 0.8 0.8], ...
              'Position', [175 20 100 30], ...
              'Callback', @(~,~) close(f));
end
